name: Abceed
options:
  minimumXcodeGenVersion: 2.14.0
  deploymentTarget: 13.2
  bundleIdPrefix: jp.toshi0383
targets:
  Abceed:
    platform: iOS
    type: application
    sources:
      - Abceed
    dependencies:
      - target: AbceedUI
        link: false
        embed: false
      - target: AbceedUIBundle
  AbceedSwiftUI:
    platform: iOS
    type: application
    sources:
      - AbceedSwiftUI
    settings:
      SUPPORTS_MACCATALYST: YES
    dependencies:
      - target: AbceedLogic
        link: false
        embed: false
      - target: AbceedCore
        link: false
        embed: false
      - target: AbceedUIBundle
      - package: SDWebImageSwiftUI
        product: SDWebImage
      - package: SDWebImageSwiftUI
        product: SDWebImageSwiftUI
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: Realm
        product: Realm
      - package: Realm
        product: RealmSwift
  UILibrary:
    platform: iOS
    type: application
    sources:
      - UILibrary
    dependencies:
      - target: AbceedUI
        link: false
        embed: false
      - target: AbceedUIBundle
      - target: TestHelper
  AbceedCore:
    platform: iOS
    type: framework
    settings:
      MACH_O_TYPE: staticlib
    sources:
      - AbceedCore/
    dependencies:
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
  AbceedCoreTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - AbceedCoreTests/
    dependencies:
      - target: AbceedCore
        link: false
        embed: false
      - target: TestHelper
    scheme:
      testTargets:
        - AbceedCoreTests
      gatherCoverageData: true
  AbceedLogic:
    platform: iOS
    type: framework
    settings:
      MACH_O_TYPE: staticlib
    sources:
      - AbceedLogic/
    dependencies:
      - target: AbceedCore
        link: false
        embed: false
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: Realm
        product: Realm
      - package: Realm
        product: RealmSwift
  AbceedLogicTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - AbceedLogicTests/
    dependencies:
      - target: AbceedLogic
        link: false
        embed: false
      - target: TestHelper
    scheme:
      testTargets:
        - AbceedLogicTests
      gatherCoverageData: true
  AbceedUI:
    platform: iOS
    type: framework
    settings:
      MACH_O_TYPE: staticlib
    sources:
      - AbceedUI/
    dependencies:
      - package: Nuke
      - package: RxNuke
      - carthage: SwipeMenuViewController
      - target: AbceedLogic
        link: false
        embed: false
  TestHelper:
    platform: iOS
    type: framework
    sources:
      - TestHelper/
  AbceedUIBundle:
    platform: iOS
    type: bundle
    sources:
      - AbceedUIBundle/
packages:
  Nuke:
    url: https://github.com/kean/Nuke
    majorVersion: 8.4.1
  RxNuke:
    url: https://github.com/kean/RxNuke
    majorVersion: 0.11.0
  Realm:
    url: https://github.com/realm/realm-cocoa
    majorVersion: 4.4.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    majorVersion: 5.1.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    majorVersion: 1.1.0
